use std::{env, fs, time::SystemTime};

use rlbot_flat_dts::flat::{CorePacket, InterfacePacket};
use ts_rs::TS;

const OUTPUT_FILE: &str = "./plugin/rlbot.d.ts";

fn timestamp_µs_hex() -> String {
    let micros = SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .expect("time went backwards")
        .as_micros();

    format!("{:x}", micros)
}

fn main() {
    let temp_dir = env::temp_dir().join(timestamp_µs_hex());
    fs::create_dir_all(&temp_dir).expect("create temp dir");

    InterfacePacket::export_all_to(&temp_dir).expect("export interfacepacket deps");
    CorePacket::export_all_to(&temp_dir).expect("export corepacket deps");

    let mut outstr = String::from(
        "// This file is @generated by `build.rs` with the help of https://github.com/Aleph-Alpha/ts-rs",
    );

    for file in fs::read_dir(&temp_dir).expect("read temp dir") {
        let file = file.unwrap();
        let cleaned: String = fs::read_to_string(file.path())
            .expect("read file")
            .lines()
            .filter(|x| {
                !(x.starts_with("import") || x.starts_with("// This file was generated by"))
            })
            .collect::<Vec<_>>()
            .join("\n");
        outstr.push_str(&cleaned);
    }

    fs::remove_dir_all(&temp_dir).expect("remove temp dir");

    fs::write(OUTPUT_FILE, outstr).expect("write output file");

    println!("cargo:rerun-if-changed=plugin/index.ts");
    println!("cargo:rerun-if-changed=plugin/plugin.ts");

    std::process::Command::new("bun")
        .args(["build", "plugin/index.ts", "--outfile=plugin/bundle.js"])
        .status()
        .expect("failed to run bun build, make sure it's installed and in path");

    println!("cargo:rerun-if-changed=runner/src/index.ts");
    println!("cargo:rerun-if-changed=runner/src/plugin.ts");
    println!("cargo:rerun-if-changed=runner/build.ts");
    println!("cargo:rerun-if-changed=runner/package.json");

    std::process::Command::new("bun")
        .current_dir("./runner")
        .args(["run", "build"])
        .status()
        .expect("failed to run bun, make sure it's installed and in path");
}
